// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: MotorController_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_StartButtonLabel;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_StopButtonLabel;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_ImmediateStopButtonLabel;
// CUSTOM VARIABLES

lv_obj_t * operation_params_cont;
lv_obj_t * operation_params_input_cont;
lv_obj_t * operation_mode_cont;
lv_obj_t * control_buttons_cont;
lv_obj_t * buttons_telemetry_cont;
lv_obj_t * control_buttons_cont;
lv_obj_t * telemetry_cont;

lv_obj_t * rotate_per_sec_label;
lv_obj_t * carriage_movement_label;
lv_obj_t * general_winding_length_label;
lv_obj_t * current_speed_label;
lv_obj_t * current_winding_length_label;
lv_obj_t * used_cable_total_length_label;
lv_obj_t * operating_time_label;

lv_obj_t * rotate_per_sec_entry;
lv_obj_t * carriage_movement_entry;
lv_obj_t * general_winding_length_entry;

lv_obj_t * start_button;
lv_obj_t * stop_button;
lv_obj_t * immediate_stop_button;
lv_obj_t * manual_acceleration_button;
lv_obj_t * manual_deceleration_button;
lv_obj_t * home_point_button;
lv_obj_t * reset_info_panel_button;

lv_obj_t * start_button_label;
lv_obj_t * stop_button_label;
lv_obj_t * immediate_stop_button_label;
lv_obj_t * manual_acceleration_button_label;
lv_obj_t * manual_deceleration_button_label;
lv_obj_t * home_point_button_label;
lv_obj_t * reset_info_panel_button_label;

lv_obj_t * grinding_mode_checkbox;
lv_obj_t * conical_winding_checkbox;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartMotors(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StopMotors(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ImmediateStop(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
