// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: MotorController_UI

#include "ui.h"
#include "ui_helpers.h"
#include "uart_manager.h"
#include <stdio.h>
#include "cJSON.h"
#include "esp_log.h"
#include "esp_heap_caps.h" // Для esp_get_free_heap_size
#include "freertos/FreeRTOS.h" // Для BaseType_t і pdPASS
#include "esp_timer.h"

#define TAG "UI_UPDATE"
///////////////////// VARIABLES ////////////////////

// Структура для передачі даних в асинхронний callback
typedef struct {
    char rotation_speed[8];
    char winding_step[8];
    char total_length[12];
    char current_speed[16];
    char current_winding_length[16];
    char used_cable_total_length[16];
    char operating_time[32];
    char switch_dir_delay_mm[8];
    char layers_to_increase_delay[8];
    bool grinding_status;
    bool conical_winding_status;
    bool revers_conical_winding_status;
} ui_data_t;

static ui_data_t ui_data_for_update = {0};

// Структура для передачі modal і checkbox
typedef struct {
    lv_obj_t *modal;
    lv_obj_t *checkbox;
} dialog_data_t;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_StartButtonLabel;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_StopButtonLabel;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_ImmediateStopButtonLabel;
// CUSTOM VARIABLES

lv_obj_t * operation_params_cont;
lv_obj_t * operation_params_input_cont;
lv_obj_t * operation_mode_cont;
lv_obj_t * control_buttons_cont;
lv_obj_t * buttons_telemetry_cont;
lv_obj_t * control_buttons_cont;
lv_obj_t * telemetry_cont;

lv_obj_t * rotate_per_sec_label;
lv_obj_t * carriage_movement_label;
lv_obj_t * general_winding_length_label;
lv_obj_t * current_speed_label;
lv_obj_t * current_winding_length_label;
lv_obj_t * used_cable_total_length_label;
lv_obj_t * operating_time_label;

lv_obj_t * rotate_per_sec_entry;
lv_obj_t * carriage_movement_entry;
lv_obj_t * general_winding_length_entry;
lv_obj_t * revers_conical_layers_entry;
lv_obj_t * revers_conical_delay_mm_entry;

lv_obj_t * start_button;
lv_obj_t * stop_button;
lv_obj_t * immediate_stop_button;
lv_obj_t * manual_acceleration_button;
lv_obj_t * manual_deceleration_button;
lv_obj_t * home_point_button;
lv_obj_t * reset_info_panel_button;

lv_obj_t * start_button_label;
lv_obj_t * stop_button_label;
lv_obj_t * immediate_stop_button_label;
lv_obj_t * manual_acceleration_button_label;
lv_obj_t * manual_deceleration_button_label;
lv_obj_t * home_point_button_label;
lv_obj_t * reset_info_panel_button_label;

lv_obj_t * grinding_mode_checkbox;
lv_obj_t * conical_winding_checkbox;
lv_obj_t * revers_conical_winding_checkbox;

esp_timer_handle_t ui_asycn_update_timer;


void start_button_cliked(lv_event_t * e);
void stop_button_cliked(lv_event_t * e);
void accelerate_button_clicked(lv_event_t * e);
void decelerate_button_clicked(lv_event_t * e);
void immediate_stop_button_clicked(lv_event_t * e);
void home_point_button_clicked(lv_event_t * e);

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

static void async_update_task() {
    
    static bool is_firts_update = true;

    char buffer[48];

    // Перевірка ініціалізації об’єктів LVGL
    if (!current_speed_label || !current_winding_length_label || !used_cable_total_length_label || !operating_time_label) {
        ESP_LOGE(TAG, "One or more UI labels are not initialized");
        return;
    }
    if ((!rotate_per_sec_entry || !carriage_movement_entry || !general_winding_length_entry) && is_firts_update) {
        ESP_LOGE(TAG, "One or more UI entry are not initialized");
        return;
    }

    if(is_firts_update) {
        if(ui_data_for_update.current_speed[0]) {
            snprintf(buffer, sizeof(buffer), "%s", ui_data_for_update.rotation_speed);
            lv_textarea_add_text(rotate_per_sec_entry, buffer);
        }
        if(ui_data_for_update.winding_step[0]) {
            snprintf(buffer, sizeof(buffer), "%s", ui_data_for_update.winding_step);
            lv_textarea_add_text(carriage_movement_entry, buffer);
        }
        if(ui_data_for_update.total_length[0]) {
            snprintf(buffer, sizeof(buffer), "%s", ui_data_for_update.total_length);
            lv_textarea_add_text(general_winding_length_entry, buffer);
        }
        if(ui_data_for_update.switch_dir_delay_mm[0]) {
            snprintf(buffer, sizeof(buffer), "%s", ui_data_for_update.switch_dir_delay_mm);
            lv_textarea_add_text(revers_conical_delay_mm_entry, buffer);
        }
        if(ui_data_for_update.layers_to_increase_delay[0]) {
            snprintf(buffer, sizeof(buffer), "%s", ui_data_for_update.layers_to_increase_delay);
            lv_textarea_add_text(revers_conical_layers_entry, buffer);
        }
        if(ui_data_for_update.grinding_status) {
            lv_obj_add_state(grinding_mode_checkbox, LV_STATE_CHECKED);
        } else {
            lv_obj_add_state(grinding_mode_checkbox, LV_STATE_DEFAULT);
        }
        if(ui_data_for_update.conical_winding_status) {
            lv_obj_add_state(conical_winding_checkbox, LV_STATE_CHECKED);
        } else {
            lv_obj_add_state(conical_winding_checkbox, LV_STATE_DEFAULT);
        }
        if(ui_data_for_update.revers_conical_winding_status) {
            lv_obj_add_state(revers_conical_winding_checkbox, LV_STATE_CHECKED);
        } else {
            lv_obj_add_state(revers_conical_winding_checkbox, LV_STATE_DEFAULT);
        }
        is_firts_update = false;
    }

    // Speed: "Speed: X.XX rps"
    if (ui_data_for_update.current_speed[0] && strcmp(ui_data_for_update.current_speed, "N/A") != 0) {
        snprintf(buffer, sizeof(buffer), "Speed: %s rps", ui_data_for_update.current_speed);
        lv_label_set_text(current_speed_label, buffer);
    }

    // Current Length: "Current Length: XXXXX,XX m"
    if (ui_data_for_update.current_winding_length[0] && strcmp(ui_data_for_update.current_winding_length, "N/A") != 0) {
        char temp[16];
        strncpy(temp, ui_data_for_update.current_winding_length, sizeof(temp) - 1);
        temp[sizeof(temp) - 1] = '\0';
        char *comma_ptr = strchr(temp, '.');
        if (comma_ptr) *comma_ptr = ',';
        snprintf(buffer, sizeof(buffer), "Current Length: %s m", temp);
        lv_label_set_text(current_winding_length_label, buffer);
    }

    // Used Length: "Used Length: XXXXX,XX m"
    if (ui_data_for_update.used_cable_total_length[0] && strcmp(ui_data_for_update.used_cable_total_length, "N/A") != 0) {
        char temp[16];
        strncpy(temp, ui_data_for_update.used_cable_total_length, sizeof(temp) - 1);
        temp[sizeof(temp) - 1] = '\0';
        char *comma_ptr = strchr(temp, '.');
        if (comma_ptr) *comma_ptr = ',';
        snprintf(buffer, sizeof(buffer), "Used Length: %s m", temp);
        lv_label_set_text(used_cable_total_length_label, buffer);
    }

    // Operating Time: "Operating Time: HH:MM:SS"
    if (ui_data_for_update.operating_time[0] && strcmp(ui_data_for_update.operating_time, "N/A") != 0) {
        int total_seconds = atoi(ui_data_for_update.operating_time);
        if (total_seconds >= 0) {
            int hours = total_seconds / 3600;
            int minutes = (total_seconds % 3600) / 60;
            int seconds = total_seconds % 60;
            snprintf(buffer, sizeof(buffer), "Operating Time: %02d:%02d:%02d", hours, minutes, seconds);
            lv_label_set_text(operating_time_label, buffer);
        }
    }
}

static void dialog_event_handler(lv_event_t *e) {
    dialog_data_t *data = lv_event_get_user_data(e);
    lv_obj_t *btn = lv_event_get_target(e);
    const char *txt = lv_label_get_text(lv_obj_get_child(btn, 0));

    if (strcmp(txt, "OK") == 0) {
        bool is_checked = lv_obj_has_state(data->checkbox, LV_STATE_CHECKED);
        if (is_checked) {
            uart_send_command("{\"command\": \"reset_all\"}");
        } else {
            uart_send_command("{\"command\": \"reset\"}");
        }
    } else if (strcmp(txt, "Cancel") == 0) {
        ESP_LOGI("Dialog", "Reset canceled");
    }

    lv_obj_del(data->modal);
    free(data); // Звільняємо пам’ять структури
}

void conical_winding_checkbox_handler(lv_event_t *e) {
    lv_obj_t *checkbox = lv_event_get_target(e); // Отримуємо об’єкт, який викликав подію
    bool is_checked = lv_obj_has_state(checkbox, LV_STATE_CHECKED);

    if (is_checked) {
        ESP_LOGI("CHECKBOX", "Conical winding enabled");
        uart_send_command("{\"command\": \"conical_on\"}");
    } else {
        ESP_LOGI("CHECKBOX", "Conical winding disabled");
        uart_send_command("{\"command\": \"conical_off\"}");
    }
}

void grinding_mode_checkbox_handler(lv_event_t *e) {
    lv_obj_t *checkbox = lv_event_get_target(e); // Отримуємо об’єкт, який викликав подію
    bool is_checked = lv_obj_has_state(checkbox, LV_STATE_CHECKED);

    if (is_checked) {
        ESP_LOGI("CHECKBOX", "Grinding mode enabled");
        uart_send_command("{\"command\": \"grinding_on\"}");
    } else {
        ESP_LOGI("CHECKBOX", "Grinding mode disabled");
        uart_send_command("{\"command\": \"grinding_off\"}");
    }
}

void revers_conical_winding_checkbox_handler(lv_event_t *e) {
    lv_obj_t *checkbox = lv_event_get_target(e); // Отримуємо об’єкт, який викликав подію
    bool is_checked = lv_obj_has_state(checkbox, LV_STATE_CHECKED);

    if (is_checked) {
        ESP_LOGI("CHECKBOX", "Revers conical mode enabled");
        uart_send_command("{\"command\": \"revers_conical_on\"}");
    } else {
        ESP_LOGI("CHECKBOX", "Revers conical mode disabled");
        uart_send_command("{\"command\": \"revers_conical_off\"}");
    }
}

static void create_confirm_dialog(const char *message) {
    // Модальне тло
    lv_obj_t *modal = lv_obj_create(ui_Screen1);
    lv_obj_add_flag(modal, LV_OBJ_FLAG_FLOATING);
    lv_obj_set_size(modal, LV_PCT(100), LV_PCT(100));
    lv_obj_set_style_bg_color(modal, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(modal, LV_OPA_50, 0);

    // Контейнер діалогу (вертикальна Flex-розмітка)
    lv_obj_t *dialog = lv_obj_create(modal);
    lv_obj_set_size(dialog, LV_PCT(40), LV_PCT(50));
    lv_obj_center(dialog);
    lv_obj_set_style_bg_color(dialog, lv_color_hex(0x2b2b2b), 0);
    lv_obj_set_style_border_width(dialog, 0, 0);
    lv_obj_set_style_pad_all(dialog, 10, 0);
    lv_obj_set_layout(dialog, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(dialog, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(dialog, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(dialog, 0, 0);

    // Контейнер для тексту
    lv_obj_t *text_cont = lv_obj_create(dialog);
    lv_obj_set_size(text_cont, LV_PCT(100), LV_SIZE_CONTENT);
    lv_obj_set_style_bg_opa(text_cont, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(text_cont, 0, 0);

    lv_obj_t *label = lv_label_create(text_cont);
    lv_label_set_text(label, message);
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_width(label, LV_PCT(100));

    // Контейнер для прапорця
    lv_obj_t *checkbox_cont = lv_obj_create(dialog);
    lv_obj_set_size(checkbox_cont, LV_PCT(100), LV_SIZE_CONTENT);
    lv_obj_set_layout(checkbox_cont, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(checkbox_cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(checkbox_cont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(checkbox_cont, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(checkbox_cont, 0, 0);
    lv_obj_set_style_pad_column(checkbox_cont, 5, 0);

    lv_obj_t *checkbox = lv_checkbox_create(checkbox_cont);
    lv_checkbox_set_text(checkbox, "Reset Total Used Length");
    lv_obj_set_style_text_align(checkbox, LV_TEXT_ALIGN_LEFT, 0);

    // Контейнер для кнопок
    lv_obj_t *btn_cont = lv_obj_create(dialog);
    lv_obj_set_size(btn_cont, LV_PCT(100), LV_SIZE_CONTENT);
    lv_obj_set_layout(btn_cont, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(btn_cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(btn_cont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(btn_cont, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(btn_cont, 0, 0);
    lv_obj_set_style_pad_column(btn_cont, 10, 0);

    // Створюємо структуру для передачі даних
    dialog_data_t *data = malloc(sizeof(dialog_data_t));
    data->modal = modal;
    data->checkbox = checkbox;

    // Кнопка "OK"
    lv_obj_t *btn_ok = lv_btn_create(btn_cont);
    lv_obj_set_size(btn_ok, 80, 40);
    lv_obj_add_event_cb(btn_ok, dialog_event_handler, LV_EVENT_CLICKED, data);
    lv_obj_t *label_ok = lv_label_create(btn_ok);
    lv_label_set_text(label_ok, "OK");
    lv_obj_center(label_ok);

    // Кнопка "Cancel"
    lv_obj_t *btn_cancel = lv_btn_create(btn_cont);
    lv_obj_set_size(btn_cancel, 80, 40);
    lv_obj_add_event_cb(btn_cancel, dialog_event_handler, LV_EVENT_CLICKED, data);
    lv_obj_t *label_cancel = lv_label_create(btn_cancel);
    lv_label_set_text(label_cancel, "Cancel");
    lv_obj_center(label_cancel);
}

void update_ui_callback(const char *data) {
    ESP_LOGI(TAG, "Received data: %s", data);
    if (!data || data[0] == '\0') {
        ESP_LOGE(TAG, "No data received");
        return;
    }

    // Парсимо JSON
    cJSON *root = cJSON_Parse(data);
    if (!root) {
        ESP_LOGE(TAG, "Failed to parse JSON: %s", cJSON_GetErrorPtr());
        return;
    }


    static bool is_first_update = true;

    // Ініціалізація значень за замовчуванням
    strcpy(ui_data_for_update.current_speed, "N/A");
    strcpy(ui_data_for_update.current_winding_length, "N/A");
    strcpy(ui_data_for_update.used_cable_total_length, "N/A");
    strcpy(ui_data_for_update.operating_time, "N/A");

    if(is_first_update) {
        cJSON *rotation_speed = cJSON_GetObjectItem(root, "rotation_speed_entry");
        if (rotation_speed && cJSON_IsNumber(rotation_speed)) {
            if(rotation_speed->valuedouble <= 0) {
                strcpy(ui_data_for_update.rotation_speed, "");
            } else {
                snprintf(ui_data_for_update.rotation_speed, sizeof(ui_data_for_update.rotation_speed), "%d", rotation_speed->valueint);
            }
        }

        cJSON *winding_step = cJSON_GetObjectItem(root, "winding_step_entry");
        if (winding_step && cJSON_IsNumber(winding_step)) {
            if(winding_step->valuedouble <= 0) {
                strcpy(ui_data_for_update.winding_step, "");
            } else {
                snprintf(ui_data_for_update.winding_step, sizeof(ui_data_for_update.winding_step), "%.2f", winding_step->valuedouble);
            }
        }

        cJSON *total_length = cJSON_GetObjectItem(root, "total_length_entry");
        if (total_length && cJSON_IsNumber(total_length)) {
            if(total_length->valueint <= 0) {
                strcpy(ui_data_for_update.total_length, "");
            } else {
                snprintf(ui_data_for_update.total_length, sizeof(ui_data_for_update.total_length), "%d", total_length->valueint);
            }
        }

        cJSON *grinding_status = cJSON_GetObjectItem(root, "grinding_status");
        if (grinding_status && cJSON_IsNumber(grinding_status)) {
            if(grinding_status->valueint) {
                ui_data_for_update.grinding_status = true;
            } else {
                ui_data_for_update.grinding_status = false;
            }
        }

        cJSON *conical_winding_status = cJSON_GetObjectItem(root, "conical_status");
        if (conical_winding_status && cJSON_IsNumber(conical_winding_status)) {
            if(conical_winding_status->valueint) {
                ui_data_for_update.conical_winding_status = true;
            } else {
                ui_data_for_update.conical_winding_status = false;
            }
        }

        cJSON *revers_conical_winding_status = cJSON_GetObjectItem(root, "revers_conical_status");
        if (revers_conical_winding_status && cJSON_IsNumber(revers_conical_winding_status)) {
            if(revers_conical_winding_status->valueint) {
                ui_data_for_update.revers_conical_winding_status = true;
            } else {
                ui_data_for_update.revers_conical_winding_status = false;
            }
        }

        cJSON *switch_dir_delay_mm = cJSON_GetObjectItem(root, "switch_dir_delay_mm");
        if (switch_dir_delay_mm && cJSON_IsNumber(switch_dir_delay_mm)) {
            if(switch_dir_delay_mm->valuedouble <= 0) {
                strcpy(ui_data_for_update.switch_dir_delay_mm, "");
            } else {
                snprintf(ui_data_for_update.switch_dir_delay_mm, sizeof(ui_data_for_update.switch_dir_delay_mm), "%.2f", switch_dir_delay_mm->valuedouble);
            }
        }

        cJSON *layers_to_increase_delay = cJSON_GetObjectItem(root, "layers_to_increase_delay");
        if (layers_to_increase_delay && cJSON_IsNumber(layers_to_increase_delay)) {
            if(layers_to_increase_delay->valueint <= 0) {
                strcpy(ui_data_for_update.layers_to_increase_delay, "");
            } else {
                snprintf(ui_data_for_update.layers_to_increase_delay, sizeof(ui_data_for_update.layers_to_increase_delay), "%d", layers_to_increase_delay->valueint);
            }
        }
        is_first_update = false;
    }

    // Витягуємо значення з JSON
    cJSON *speed = cJSON_GetObjectItem(root, "speed");
    if (speed && cJSON_IsNumber(speed)) {
        snprintf(ui_data_for_update.current_speed, sizeof(ui_data_for_update.current_speed), "%.2f", speed->valuedouble);
        ESP_LOGI(TAG, "Parsed speed: %s", ui_data_for_update.current_speed);
    }

    cJSON *winding = cJSON_GetObjectItem(root, "current_winding");
    if (winding && cJSON_IsNumber(winding)) {
        snprintf(ui_data_for_update.current_winding_length, sizeof(ui_data_for_update.current_winding_length), "%.2f", winding->valuedouble);
        //ESP_LOGI(TAG, "Parsed winding: %s", ui_data_for_update.current_winding_length);
    }

    cJSON *cable = cJSON_GetObjectItem(root, "total_cable_length");
    if (cable && cJSON_IsNumber(cable)) {
        snprintf(ui_data_for_update.used_cable_total_length, sizeof(ui_data_for_update.used_cable_total_length), "%.2f", cable->valuedouble);
        //ESP_LOGI(TAG, "Parsed cable: %s", ui_data_for_update.used_cable_total_length);
    }

    cJSON *time = cJSON_GetObjectItem(root, "time");
    if (time && cJSON_IsNumber(time)) {
        snprintf(ui_data_for_update.operating_time, sizeof(ui_data_for_update.operating_time), "%d", time->valueint);
        //ESP_LOGI(TAG, "Parsed time: %s", ui_data->operating_time);
    }

    esp_timer_start_once(ui_asycn_update_timer, 100000);

    // Очищаємо пам’ять JSON
    cJSON_Delete(root);
}

void start_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        char *json = gen_json_startup_config();
        uart_send_command(json);
        free(json);
    }
}

char* gen_json_startup_config() {
    // Створюємо JSON-об'єкт
    cJSON *root = cJSON_CreateObject();
    
    // Додаємо поля
    cJSON_AddStringToObject(root, "command", "start");
    cJSON_AddNumberToObject(root, "speed", atof(lv_textarea_get_text(rotate_per_sec_entry)));
    cJSON_AddNumberToObject(root, "carriage_movement", atof(lv_textarea_get_text(carriage_movement_entry)));
    cJSON_AddNumberToObject(root, "general_length", atof(lv_textarea_get_text(general_winding_length_entry)));
    cJSON_AddNumberToObject(root, "layers", atof(lv_textarea_get_text(revers_conical_layers_entry)));
    cJSON_AddNumberToObject(root, "delay_mm", atof(lv_textarea_get_text(revers_conical_delay_mm_entry)));
    
    // Перетворюємо в рядок
    char *json_string = cJSON_PrintUnformatted(root);
    
    // Очищуємо пам'ять
    cJSON_Delete(root);
    
    return json_string;
}

static char* gen_json_revers_conical_config() {
    // Створюємо JSON-об'єкт
    cJSON *root = cJSON_CreateObject();
    
    // Додаємо поля
    cJSON_AddStringToObject(root, "command", "set_revers_conical_params");
    cJSON_AddNumberToObject(root, "layers", atof(lv_textarea_get_text(revers_conical_layers_entry)));
    cJSON_AddNumberToObject(root, "delay_mm", atof(lv_textarea_get_text(revers_conical_delay_mm_entry)));
    
    // Перетворюємо в рядок
    char *json_string = cJSON_PrintUnformatted(root);
    
    // Очищуємо пам'ять
    cJSON_Delete(root);
    
    return json_string;
}

void accept_revers_conical_params_btn_cb(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        char *json = gen_json_revers_conical_config();
        uart_send_command(json);
        free(json);
    }
}

void stop_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uart_send_command("{\"command\": \"stop\"}");
    }
}

void accelerate_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uart_send_command("{\"command\": \"accelerate\"}");
    }
}

void decelerate_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uart_send_command("{\"command\": \"decelerate\"}");
    }
}

void immediate_stop_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uart_send_command("{\"command\": \"immediate_stop\"}");
    }
}

void home_point_button_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uart_send_command("{\"command\": \"home_point\"}");
    }
}

void reset_button_clicked(lv_event_t *e) {
    create_confirm_dialog("Are you sure you want to reset?");
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartMotors(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StopMotors(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ImmediateStop(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    uart_register_data_callback(update_ui_callback);
    ESP_LOGI("TEST DEBUG: ", "-------- TEST INFO -------\n");

    const esp_timer_create_args_t ui_asycn_update_timer_args = {
        .callback = async_update_task,
        .name = "ui_asycn_update_timer"
    };

    esp_timer_create(&ui_asycn_update_timer_args, &ui_asycn_update_timer);
    uart_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
