// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: MotorController_UI

#ifndef _MOTORCONTROLLER_UI_UI_H
#define _MOTORCONTROLLER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_StartButtonLabel;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_StopButtonLabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_ImmediateStopButtonLabel;
// CUSTOM VARIABLES

// --- Containers ---
extern lv_obj_t * cont_main;


extern lv_obj_t * operation_params_cont;
extern lv_obj_t * operation_params_input_cont;
extern lv_obj_t * cont_operation_mode;
extern lv_obj_t * control_buttons_cont;
extern lv_obj_t * buttons_telemetry_cont;
extern lv_obj_t * control_buttons_cont;
extern lv_obj_t * telemetry_cont;

// --- Labels ---
extern lv_obj_t * rotate_per_sec_label;
extern lv_obj_t * carriage_movement_label;
extern lv_obj_t * general_winding_length_label;
extern lv_obj_t * current_speed_label;
extern lv_obj_t * current_winding_length_label;
extern lv_obj_t * used_cable_total_length_label;
extern lv_obj_t * operating_time_label;

// --- Entry (Textarea) ---
extern lv_obj_t * rotate_per_sec_entry;
extern lv_obj_t * carriage_movement_entry;
extern lv_obj_t * general_winding_length_entry;
extern lv_obj_t * revers_conical_layers_entry;
extern lv_obj_t * revers_conical_delay_mm_entry;

// --- Buttons ---
extern lv_obj_t * start_button;
extern lv_obj_t * stop_button;
extern lv_obj_t * immediate_stop_button;
extern lv_obj_t * manual_acceleration_button;
extern lv_obj_t * manual_deceleration_button;
extern lv_obj_t * home_point_button;
extern lv_obj_t * reset_info_panel_button;

// --- Buttons Labels ---
extern lv_obj_t * start_button_label;
extern lv_obj_t * stop_button_label;
extern lv_obj_t * immediate_stop_button_label;
extern lv_obj_t * manual_acceleration_button_label;
extern lv_obj_t * manual_deceleration_button_label;
extern lv_obj_t * home_point_button_label;
extern lv_obj_t * reset_info_panel_button_label;

// --- Checkboxes ---
extern lv_obj_t * grinding_mode_checkbox;
extern lv_obj_t * conical_winding_checkbox;
extern lv_obj_t * revers_conical_winding_checkbox;

// +++++ Reset Confirm Dialog +++++

// --- 

void start_button_clicked(lv_event_t * e);
void stop_button_clicked(lv_event_t * e);
void accelerate_button_clicked(lv_event_t * e);
void decelerate_button_clicked(lv_event_t * e);
void immediate_stop_button_clicked(lv_event_t * e);
void home_point_button_clicked(lv_event_t * e);
void reset_button_clicked(lv_event_t *e);
void accept_revers_conical_params_btn_cb(lv_event_t *e);
void conical_winding_checkbox_handler(lv_event_t *e);
void grinding_mode_checkbox_handler(lv_event_t *e);
void revers_conical_winding_checkbox_handler(lv_event_t *e);

char* gen_json_startup_config();

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
